package com.webapp.shoppingwebsite.dao;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.Date;
import java.util.Set;


@DynamoDBTable(tableName = "users")
public class User{


    public static final String ROLE_USER = "ROLE_USER";
    public static final String ROLE_ADMIN = "ROLE_ADMIN";

    private String email;
    private String userid;
    private String name;
    private String imageUrl;
    private Boolean enabled;
    private String password;
    private AuthProvider provider;
    private String providerId;
    private Set<String> role;
    private Date createddate ;
    private Date modifieddate ;

    @DynamoDBHashKey(attributeName = "email")
    public String getEmail() {
        return email;
    }

    @DynamoDBIndexHashKey(attributeName = "userid", globalSecondaryIndexName = "useridx_id")
    @DynamoDBAutoGeneratedKey
    public String getUserid() { return userid; }

   @DynamoDBAttribute
    public String getName() {
        return name;
    }

    @DynamoDBAttribute
    public String getImageUrl() {
        return imageUrl;
    }

    @DynamoDBAttribute
    public Boolean getEnabled() {
        return enabled;
    }

    @DynamoDBAttribute
    public String getPassword() {
        return password;
    }

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    public AuthProvider getProvider() {
        return provider;
    }

    @DynamoDBAttribute
    public String getProviderId() {
        return providerId;
    }

    @DynamoDBAttribute
    public Set<String> getRole() {
        return role;
    }

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
    public Date getCreateddate() { return createddate; }

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.ALWAYS)
    public Date getModifieddate() { return modifieddate; }


    public void setEmail(String email) {
        this.email = email;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setProvider(AuthProvider provider) {
        this.provider = provider;
    }

    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }

    public void setRole(Set<String> role) {
        this.role = role;
    }

    public void setCreateddate(Date createddate) { this.createddate = createddate; }

    public void setModifieddate(Date modifieddate) { this.modifieddate = modifieddate; }
}
